# Generated by Django 4.0.3 on 2022-03-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stations',
            options={'verbose_name': 'estação FM', 'verbose_name_plural': 'estação FM'},
        ),
        migrations.AlterField(
            model_name='stations',
            name='entidade',
            field=models.CharField(max_length=100, verbose_name='Nome da entidade'),
        ),
        migrations.AlterField(
            model_name='stations',
            name='frequencia',
            field=models.CharField(max_length=50, verbose_name='Frequência'),
        ),
        migrations.AlterField(
            model_name='stations',
            name='localidade',
            field=models.CharField(max_length=50, verbose_name='Localidade'),
        ),
        migrations.AlterField(
            model_name='stations',
            name='uf',
            field=models.CharField(choices=[('BA', 'Bahia'), ('PB', 'Paraíba'), ('AL', 'Alagoas'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('MG', 'Minas Gerais'), ('PE', 'Pernambuco'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SE', 'Sergipe'), ('AC', 'Acre'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('SP', 'São Paulo'), ('MA', 'Maranhão'), ('PA', 'Pará'), ('PR', 'Paraná'), ('PI', 'Piauí'), ('RN', 'Rio Grande do Norte'), ('TO', 'Tocantins'), ('CE', 'Ceará'), ('RJ', 'Rio de Janeiro'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('GO', 'Goiás')], max_length=2, verbose_name='Estado'),
        ),
    ]
