# Generated by Django 4.0.3 on 2022-03-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_stations_frequencia_alter_stations_uf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='frequencia',
            field=models.CharField(max_length=50, verbose_name='Frequência'),
        ),
    ]
