# Generated by Django 4.0.3 on 2022-04-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_stations_frequencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='stations',
            name='CEP_Corr',
            field=models.CharField(default='', max_length=100, verbose_name='CEP_Corr'),
        ),
        migrations.AddField(
            model_name='stations',
            name='CEP_Entidade',
            field=models.CharField(default='', max_length=100, verbose_name='CEP_Entidade'),
        ),
        migrations.AddField(
            model_name='stations',
            name='CEP_Estacao',
            field=models.CharField(default='', max_length=100, verbose_name='CEP_Estacao'),
        ),
        migrations.AddField(
            model_name='stations',
            name='CNPJ',
            field=models.CharField(default='', max_length=100, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='stations',
            name='Cidade_Corr',
            field=models.CharField(default='', max_length=100, verbose_name='Cidade_Corr'),
        ),
        migrations.AddField(
            model_name='stations',
            name='Cidade_Entidade',
            field=models.CharField(default='', max_length=100, verbose_name='Cidade_Entidade'),
        ),
        migrations.AddField(
            model_name='stations',
            name='Classe',
            field=models.CharField(default='', max_length=100, verbose_name='Classe'),
        ),
        migrations.AddField(
            model_name='stations',
            name='End_Corr',
            field=models.CharField(default='', max_length=100, verbose_name='End_Corr'),
        ),
        migrations.AddField(
            model_name='stations',
            name='End_Entidade',
            field=models.CharField(default='', max_length=100, verbose_name='End_Entidade'),
        ),
        migrations.AddField(
            model_name='stations',
            name='End_Estacao',
            field=models.CharField(default='', max_length=100, verbose_name='End_Estacao'),
        ),
        migrations.AddField(
            model_name='stations',
            name='Latitude',
            field=models.CharField(default='', max_length=100, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='stations',
            name='Longitude',
            field=models.CharField(default='', max_length=100, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='stations',
            name='N_Estacao',
            field=models.CharField(default='', max_length=100, verbose_name='N_Estacao'),
        ),
        migrations.AddField(
            model_name='stations',
            name='N_Fistel',
            field=models.CharField(default='', max_length=100, verbose_name='N_Fistel'),
        ),
        migrations.AddField(
            model_name='stations',
            name='Nome_Fantasia',
            field=models.CharField(default='', max_length=100, verbose_name='Nome_Entidade'),
        ),
        migrations.AddField(
            model_name='stations',
            name='Potencia',
            field=models.CharField(default='', max_length=100, verbose_name='Potencia'),
        ),
        migrations.AddField(
            model_name='stations',
            name='Prefixo',
            field=models.CharField(default='', max_length=100, verbose_name='Prefixo'),
        ),
        migrations.AddField(
            model_name='stations',
            name='UF_Corr',
            field=models.CharField(default='', max_length=100, verbose_name='UF_Corr'),
        ),
        migrations.AddField(
            model_name='stations',
            name='UF_Entidade',
            field=models.CharField(default='', max_length=100, verbose_name='UF_Entidade'),
        ),
    ]
