# Generated by Django 4.0.3 on 2022-04-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_stations_cep_corr_stations_cep_entidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stations',
            name='Nome_Fantasia',
        ),
    ]
