# Generated by Django 4.0.3 on 2022-04-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_stations_nome_fantasia'),
    ]

    operations = [
        migrations.AddField(
            model_name='stations',
            name='Nome_Entidade',
            field=models.CharField(default='', max_length=100, verbose_name='Nome_Entidade'),
        ),
    ]
